# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-28 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20180727_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='county',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
