# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-28 12:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auto_20180728_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quickquote',
            name='board_actions_last_10_years',
        ),
        migrations.RemoveField(
            model_name='quickquote',
            name='claims_last_10_years',
        ),
        migrations.RemoveField(
            model_name='quickquote',
            name='closed_claims',
        ),
        migrations.RemoveField(
            model_name='quickquote',
            name='cosmetic_elective_percentage',
        ),
        migrations.RemoveField(
            model_name='quickquote',
            name='cosmetic_recon_percentage',
        ),
        migrations.RemoveField(
            model_name='quickquote',
            name='cosmetic_surgery',
        ),
        migrations.RemoveField(
            model_name='quickquote',
            name='current_carrier',
        ),
        migrations.RemoveField(
            model_name='quickquote',
            name='entity_coverage',
        ),
        migrations.RemoveField(
            model_name='quickquote',
            name='entity_note',
        ),
        migrations.RemoveField(
            model_name='quickquote',
            name='expiring_premium',
        ),
        migrations.RemoveField(
            model_name='quickquote',
            name='note',
        ),
        migrations.RemoveField(
            model_name='quickquote',
            name='open_claims',
        ),
        migrations.RemoveField(
            model_name='quickquote',
            name='primary_practice',
        ),
        migrations.RemoveField(
            model_name='quickquote',
            name='prior_acts_effective_date',
        ),
        migrations.RemoveField(
            model_name='quickquote',
            name='prior_acts_retroactive_date',
        ),
        migrations.RemoveField(
            model_name='quickquote',
            name='professional_coverage',
        ),
        migrations.RemoveField(
            model_name='quickquote',
            name='professional_note',
        ),
        migrations.RemoveField(
            model_name='quickquote',
            name='secondary_practice',
        ),
        migrations.RemoveField(
            model_name='quickquote',
            name='weekly_deliveries',
        ),
        migrations.RemoveField(
            model_name='quickquote',
            name='weekly_hours',
        ),
        migrations.RemoveField(
            model_name='quickquote',
            name='weekly_patients',
        ),
        migrations.RemoveField(
            model_name='quickquote',
            name='weekly_procedures',
        ),
        migrations.RemoveField(
            model_name='quickquote',
            name='weekly_reads',
        ),
    ]
