# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-30 09:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import portal.fields.percentage


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_auto_20180728_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='quickquote',
            name='board_actions_last_10_years',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quickquote',
            name='claims_last_10_years',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quickquote',
            name='closed_claims',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quickquote',
            name='cosmetic_elective_percentage',
            field=portal.fields.percentage.PercentageField(default=0),
        ),
        migrations.AddField(
            model_name='quickquote',
            name='cosmetic_recon_percentage',
            field=portal.fields.percentage.PercentageField(default=0),
        ),
        migrations.AddField(
            model_name='quickquote',
            name='cosmetic_surgery',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='portal.Procedure'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quickquote',
            name='current_carrier',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='quickquote',
            name='entity_coverage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quickquote',
            name='entity_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quickquote',
            name='expiring_premium',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='quickquote',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quickquote',
            name='open_claims',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quickquote',
            name='primary_practice',
            field=models.ManyToManyField(related_name='primary_address', to='portal.Address'),
        ),
        migrations.AddField(
            model_name='quickquote',
            name='prior_acts_effective_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quickquote',
            name='prior_acts_retroactive_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quickquote',
            name='professional_coverage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quickquote',
            name='professional_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quickquote',
            name='secondary_practice',
            field=models.ManyToManyField(related_name='secondary_address', to='portal.Address'),
        ),
        migrations.AddField(
            model_name='quickquote',
            name='weekly_deliveries',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quickquote',
            name='weekly_hours',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quickquote',
            name='weekly_patients',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quickquote',
            name='weekly_procedures',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quickquote',
            name='weekly_reads',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
